# Site settings
# title appears in the header
title: corey oglesby
# description and keywords for meta tags
description: Corey Oglesby | poet, musician, visual artist
keywords: "poetry, music, visual arts, pacific northwest"
# add the full url for the github repository
repo: "https://github.com/coroglesby/corey-new-site"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://coroglesby.github.io/corey-new-site/
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /corey-new-site

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "default"
# Build settings
markdown: kramdown
